export const accessArrangements = [
  { id: 'extraTime', label: 'Extra time' },
  { id: 'reader', label: 'Reader' },
  { id: 'computerReader', label: 'Computer reader' },
  { id: 'scribe', label: 'Scribe' },
  { id: 'speechRecognition', label: 'Speech recognition technology' },
  { id: 'prompter', label: 'Prompter' },
  { id: 'restBreaks', label: 'Supervised rest breaks' },
  { id: 'wordProcessor', label: 'Word processor' },
  { id: 'smallGroupRoom', label: 'Alternative rooming — smaller shared room' },
  { id: 'separateRoom', label: 'Alternative rooming — individual room (one-to-one invigilation)' },
  { id: 'colouredOverlay', label: 'Coloured overlay' },
  { id: 'colouredPaper', label: 'Coloured paper' },
  { id: 'modifiedPaper', label: 'Modified / enlarged paper' },
  { id: 'readAloud', label: 'Read aloud / examination reading pen' },
  { id: 'practicalAssistant', label: 'Practical assistant' },
  { id: 'signLanguage', label: 'Sign Language Professional' },
  { id: 'liveSpeaker', label: 'Live speaker' },
  { id: 'braille', label: 'Braille / brailler' },
  { id: 'magnifier', label: 'Low vision aid / magnifier' },
  { id: 'amplification', label: 'Amplification equipment' },
  { id: 'earDefenders', label: 'Non-electronic ear defenders / ear plugs' },
  { id: 'headphones', label: 'Non-electronic headphones' },
  { id: 'bilingualDictionary', label: 'Bilingual dictionary' },
  { id: 'other', label: 'Other' },
];
export const extraTimeOptions = ['25', '50', 'Other'];
